#!/usr/bin/env bash
# install and configure HAproxy load balancer

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy -y

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_server

backend http_server
    balance roundrobin
	server 432164-web-01 100.25.0.104:80 check
	server 432164-web-02 35.153.67.102:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start