#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sed -i 's/listen [::]:80 default_server;/listen 0.0.0.0:80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart